# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
# The analyzer can be invoked using `flutter analyze`
# See https://dart-lang.github.io/linter/lints/index.html for a list of lints
# and https://dart.dev/guides/language/analysis-options for more documentation

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
