# For documentation see https://dart.dev/tools/pub/pubspec
# or https://docs.flutter.dev/development/tools/pubspec

name: flutter_client
description: Flutter client for interacting with the Teachers Bingo API

publish_to: 'none' # Remove this line to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  material_design_icons_flutter: ^6.0.7096
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
