name: Flutter Build
on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK & Appbundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Java Environment
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Install Flutter CLI
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
        working-directory: ./flutter_client
      - run: flutter test
        working-directory: ./flutter_client
      - run: flutter build apk
        working-directory: ./flutter_client
      - run: flutter build appbundle
        working-directory: ./flutter_client
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            flutter_client/build/app/outputs/flutter-apk/app-release.apk
            flutter_client/build/app/outputs/bundle/release/app-release.aab

