name: CI flutter
on:
  push:
    paths:
      - "flutter_client/**"
      - "!**.md"
  pull_request:
    paths:
      - "flutter_client/**"
      - "!**.md"

jobs:
  lint-and-build:
    name: Lint & Build
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'wip:') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Flutter CLI
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        working-directory: ./flutter_client
        run: flutter pub get
      - name: Test app
        working-directory: ./flutter_client
        run: flutter test
