name: CI webapp
on:
  push:
    branches:
      - "main"
    paths:
      - "webapp/**"
      - "!**.md"
      - ".github/workflows/integration-webapp.yml"
  pull_request:
    paths:
      - "webapp/**"
      - "!**.md"

jobs:
  lint-and-check:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'wip:') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Nodejs Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: ./webapp/yarn.lock
      - name: Install Dependencies
        working-directory: ./webapp
        run: yarn --frozen-lockfile
      - name: Lint
        working-directory: ./webapp
        run: yarn lint --output-file eslint_report.json --format json
        continue-on-error: true
      - name: Type Check
        working-directory: ./webapp
        run: yarn tsc > typescript.log
        continue-on-error: true
      - name: Annotate Code
        uses: DerLev/eslint-annotations@v1
        with:
          eslint-report: webapp/eslint_report.json
          typescript-log: webapp/typescript.log
          error-on-warn: true
  deploy-on-vercel:
    name: Deploy on Vercel
    runs-on: ubuntu-latest
    needs: lint-and-check
    if: github.ref == 'refs/heads/main'
    environment:
      name: Preview
      url: ${{ steps.vercel_deploy.outputs.DEPLOY_URL }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Nodejs Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: ./webapp/yarn.lock
      - name: Install Vercel CLI
        run: yarn global add vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: vercel_deploy
        run: >-
          echo "DEPLOY_URL=$(
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          )" >> $GITHUB_OUTPUT
      - name: Adding Job Summary
        run: |
          echo "### Build is live in preview :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "This build got deployed on the following URLs:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- ${{ steps.vercel_deploy.outputs.DEPLOY_URL }}" >> $GITHUB_STEP_SUMMARY
          echo "- https://teachers-bingo-derlev.vercel.app/ *(latest preview url)*" >> $GITHUB_STEP_SUMMARY
