name: CI webapp
on:
  push:
    paths:
      - "webapp/**"
      - "!**.md"
      - ".github/workflows/integration-webapp.yml"
  pull_request:
    paths:
      - "webapp/**"
      - "!**.md"

jobs:
  lint-and-build:
    name: Lint & Build
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'wip:') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: ./webapp/yarn.lock
      - name: Install dependencies
        working-directory: ./webapp
        run: yarn
      - name: Lint and build app
        working-directory: ./webapp
        run: yarn build
  deploy-on-vercel:
    name: Deploy on vercel
    runs-on: ubuntu-latest
    needs: lint-and-build
    environment: Preview
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: ./webapp/yarn.lock
      - name: Install vercel cli
        run: yarn global add vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: vercel_deploy
        run: >-
          echo "DEPLOY_URL=$(
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          )" >> $GITHUB_OUTPUT
      - name: print deploy url
        run: echo ${{ steps.vercel_deploy.outputs.DEPLOY_URL }}
